server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: always
    path: /error
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  web:
    locale: bg
    locale-resolver: fixed

  messages:
    basename: messages/messages
    encoding: UTF-8

  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  sql:
    init:
      mode: never
      data-locations: classpath:data.sql

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true

  webflux:
    multipart:
      headers-charset: UTF-8
